frame_id: "world_origin"

body:
  frame_id: "fcu"

timer_main:
  rate: 1.0 # [Hz]

center:
  x: 0.0 # [m]
  y: 0.0 # [m]
  z: 2.0 # [m]

dimensions:
  x: 40.0 # [m]
  y: 20.0 # [m]

rrt:
  N_max: 15
  N_termination: 200
  N_yaw_samples: 12
  radius: 2.0 # [m]
  step_size: 1.0 # [m]
  tolerance: 0.5 # [m]

camera:
  #frame_id: "rgbd/aligned_depth_to_color_optical"
  frame_id: "rgbd/aligned_depth_to_color"
  #frame_id: "rgbd/link"
  h_fov: 1.211259 # [rad]
  width: 1280
  height: 720
  min_distance: 0.3 # [m]
  #max_distance: 12 # [m]
  max_distance: 5 # [m]

path:
  uav_radius: 1 # [m]

