# GET ALL PARAMETERS USABLE FOR CUSTOM CONFIG BY RUNNING:
## --------------------------------------------------------------
## |          rosrun mrs_uav_core get_public_params.py          #
## --------------------------------------------------------------

mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      #"rtk",
      #"gps_garmin",
      "gps_baro",
    ]

    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: "" #"garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)

  uav_manager:

    takeoff:

      during_takeoff:
        controller: "MpcController"
        tracker: "LandoffTracker"

      after_takeoff:
        controller: "MpcController" # more robust
        #controller: "Se3Controller" # more precise
        tracker: "MpcTracker"
        
      takeoff_height: 1.5

  control_manager:

    safety:

      # after not receiving odometry for more than this, the failsafe landing will trigger
      # will be overriden for ACCELERATION+ output mode
      odometry_max_missing_time: 0.5 # [s]

  constraint_manager:

    slow:

      horizontal:
        speed: 1.0
        acceleration: 1.0
        jerk: 5.0
        snap: 20.0

      vertical:

        ascending:
          speed: 1.0
          acceleration: 1.0
          jerk: 5.0
          snap: 20.0

        descending:
          speed: 1.0
          acceleration: 1.0
          jerk: 5.0
          snap: 20.0

      heading:
        speed: 1.0 # change speed
        acceleration: 1.0 # change acceleration
        jerk: 5.0
        snap: 10.0

      angular_speed:
        roll: 60.0
        pitch: 60.0
        yaw: 10.0

      tilt: 30.0 # [deg]

mrs_uav_trackers:

  landoff_tracker:

    # During takeoff, the control error should not exceed this number.
    # if control error reaches this number, the trackers stops moving the
    # reference and waits for the controllers to move the drone in closer.
    max_position_difference: 1.0
