world_origin_units: "LATLON" # {"UTM, "LATLON"}

world_origin_x: 38.7374135
world_origin_y: -9.1385655

safety_area:

  use_safety_area: false

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "world_origin"

    # convex polygon CCW
    safety_area: [
      -50, -50,
      50,  -50,
      50,  50,
      -50, 50
    ]

    max_z: 15.0
    min_z: 0.5