world_origin:

  units: "LATLON" # {"UTM, "LATLON"}

  origin_x: 39.2882567
  origin_y: -9.3231130

safety_area:

  enabled: false

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "latlon_origin"

    # polygon
    #
    # x, y [m] for any frame_name except latlon_origin
    # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
    # convex polygon CCW
    safety_area: [
      -50, -50,
      50,  -50,
      50,  50,
      -50, 50
    ]

  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "world_origin"

    max_z: 15.0
    min_z: 0.5
    
